AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

##########################################################################
#  Parameters                                                            #
##########################################################################
Parameters:
  ServerlessApiGatewayStageName:
      Type: String
      Default: dev

##########################################################################
#  Global values that are applied to all Lambda resources                #
##########################################################################
Globals:
  Function:
    MemorySize: 128
    Architectures: ["arm64"]
    Runtime: nodejs18.x
    Timeout: 29


Resources:
##########################################################################
#   Resources: Lambda function                                           #
##########################################################################
  sampleLambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ./code
        Handler: index.lambda_handler
        FunctionName: sample-lambda-function
        Events:
          RootEndpointPost:
            Type: Api
            Properties:
              RestApiId:
                Ref: ServerlessApiGateway
              Method: any
              Path: /v1
              Auth:
                Authorizer: NONE
          RootEndpointGet:
            Type: Api
            Properties:
              RestApiId:
                Ref: ServerlessApiGateway
              Method: get
              Path: /v1
              Auth:
                Authorizer: NONE
          RootEndpointOptions:
            Type: Api
            Properties:
              RestApiId:
                Ref: ServerlessApiGateway
              Method: options
              Path: /v1
              Auth:
                Authorizer: NONE
##########################################################################
#   Resources : Serverless Rest API Gateway                              #
##########################################################################
  ServerlessApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Auth:
        AddApiKeyRequiredToCorsPreflight: False
        AddDefaultAuthorizerToCorsPreflight: False
        ApiKeyRequired: False
        DefaultAuthorizer: NONE
      Cors:
          AllowOrigin: "*"
          AllowMethods:
             - GET
             - HEAD
             - OPTIONS
             - POST
             - PUT
          AllowHeaders:
             - Content-Type
             - Accept
             - Access-Control-Allow-Headers
             - Access-Control-Request-Method
             - Access-Control-Request-Headers
             - Authorization
      EndpointConfiguration:
        Type: REGIONAL
      StageName: !Ref ServerlessApiGatewayStageName
      MethodSettings:
        - ResourcePath: /{proxy+}
          HttpMethod: ANY
      Name: ServerlessApiGateway

##########################################################################
#   Outputs:                                                             #
##########################################################################
Outputs:
  RestApiEndpoint:
    Description: The REST API Gateway endpoint.
    Value:
      Fn::Sub:
        - "https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
        - ApiId: !Ref ServerlessApiGateway
          StageName: !Ref ServerlessApiGatewayStageName